# Generated by Django 3.2.16 on 2025-01-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250128_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
