# Generated by Django 3.2.16 on 2025-01-29 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20250128_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 21, 41, 36, 427417), help_text='Если установить дату в будущем — можно делать отложенные публикации.', verbose_name='Дата публикации'),
        ),
    ]
