# Generated by Django 3.2.16 on 2025-01-29 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20250129_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 21, 45, 35, 461395), help_text='Если установить дату в будущем — можно делать отложенные публикации.', verbose_name='Дата публикации'),
        ),
    ]
