# Generated by Django 3.2.16 on 2025-01-31 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250129_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 0, 28, 46, 526387), help_text='Если установить дату в будущем — можно делать отложенные публикации.', verbose_name='Дата публикации'),
        ),
    ]
